### ISSUE TITLE
ValueError: could not convert string to float: 'Illimité'

### ISSUE THREAD

**Issue by omelettedufromagee** [titilambert/pyebox#1]
Salut Thibault,

I'm using Home Assistant which embed your code.
EBOX is offering "Illimité" data and it seems to mess up with your code.

Could you do a change for that? Thank you!

`2017-07-30 21:11:29 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform ebox
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 164, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/ebox.py", line 71, in setup_platform
    ebox_data.update()
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/ebox.py", line 138, in update
    self.client.fetch_data()
  File "/usr/lib/python3.6/site-packages/pyebox/client.py", line 154, in fetch_data
    home_data = self._get_home_data()
  File "/usr/lib/python3.6/site-packages/pyebox/client.py", line 109, in _get_home_data
    home_data["limit"] = float(raw_data[1].split()[0])
ValueError: could not convert string to float: 'Illimité'`

**Comment by titilambert** [comment]
@lrogoff Thanks for reporting !
Do you know how to it this patch ?
https://github.com/titilambert/pyebox/commit/29bfe4fba8e638425f6f25bcaf72141a5672c01a
Before I create a new release for pyebox ?
